app:
  test: DEV

spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#        dialect: com.jpa.springdatajpa.config.MysqlConfig
#        format_sql: true
    show-sql: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss